name: CMake Multi-Platform CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    name: ${{ matrix.os }} with ${{ matrix.compiler }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        compiler: [gcc, clang]
        include:
          - os: windows-latest
            compiler: msvc
        exclude:
          - os: windows-latest
            compiler: gcc
          - os: windows-latest
            compiler: clang

    steps:
      - uses: actions/checkout@v3

      - name: Configure CMake
        run: cmake -S . -B _build -DCMAKE_INSTALL_PREFIX=_install

      - name: Build
        run: cmake --build _build

      - name: Install
        run: cmake --build _build --target install
